### ISSUE TITLE
Could there be an update of this EFI for the Big Sur?

### ISSUE THREAD

**Issue by wrkadri** [erenatas/Hackintosh-EFI-Z170-Radeon-VII#1]
Hello,

Could there be an update of this EFI for the Big Sur?

Thanks

**Comment by erenatas** [comment]
This is a Clover configuration. I would advise you to create your own Opencore configuration with [Opencore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html).
